### ISSUE TITLE
SpharmTools SegFaulting

### ISSUE THREAD

**Issue by zarquon42b** [NIRALUser/SPHARM-PDM#2]
Hi everyone, I am playing with your command line tools, getting acquainted with SPHARMs and realized that SpharmTools got segfaulting on me. Without gotting deeply involved into the theory, I found that setting `for( int i = 1; i < LENGTH; i++ )` to `for( int i = 1; i < LENGTH-1; i++ )` in line 1302 of Libraries/Shape/Numerics/SphericalHarmonicPolynomial.txx resolved the issue (see diff below). I do not know if this is a sensible solution, but it gives me sensible results (curves).

``` diff
--- a/Libraries/Shape/Numerics/SphericalHarmonicPolynomial.txx
+++ b/Libraries/Shape/Numerics/SphericalHarmonicPolynomial.txx
@@ -1299,7 +1299,7 @@ void SphericalHarmonicPolynomial<TDimension>::GetOneRidgePoint(unsigned int from
     std::ofstream out;
     out.open("test.txt" );
     out << "NUMBER_OF_POINTS=9999" << std::endl << "DIMENSION=3" << std::endl << "TYPE=Curve" << std::endl;
-    for( int i = 1; i < LENGTH; i++ )
+    for( int i = 1; i < LENGTH-1; i++ )
       {
       prev = current;
       current = next;
```

Best Stefan

**Comment by styner** [comment]
Hi Stefan
Thanks for pointing us to this bug. the issue is the line just below what you listed in your message:
next = values[i + 1];

next is an array of size LENGTH and thus if i= LENGTH, this line would seg-fault.

Thus, I suggest a slightly adapted correction that simply adds condition on that line. If i = LENGTH then we simply do not update the next value:
if (i < LENGTH - 1) {
  next = values[i + 1];
}

I just updated this on the repository. Btw, your version works too, but it simply skips the last loop iteration, rather than correctly handling it.

Thanks
Martin
