### ISSUE TITLE
Spatial Object code needs to be updated for ITK 5.1

### ISSUE THREAD

**Issue by sjh26** [NIRALUser/SPHARM-PDM#57]
See errors here:
http://slicer.cdash.org/viewBuildError.php?buildid=1891245

**Comment by ZhiyLiu** [comment]
Hi Sam Horvath,

Should I change ITK version in the [SuperBuild](https://github.com/NIRALUser/SPHARM-PDM/blob/master/SuperBuild/External_ITK.cmake) from 4.13.1 to 5.1.0? Because now I am having the issue as follows,
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:88:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::ValueAtInObjectSpace(const PointType&, double&, unsigned int, const string&) const’ marked ‘override’, but does not override
   bool  ValueAtInObjectSpace(const PointType & point, double & value, unsigned int depth = 0, const std::string & name = "") const override;
         ^~~~~~~~~~~~~~~~~~~~
In file included from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/SphericalHarmonicMeshSource.h:12:0,
                 from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/SphericalHarmonicMeshSource.cxx:9:
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:90:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::IsEvaluableAtInObjectSpace(const PointType&, unsigned int, const string&) const’ marked ‘override’, but does not override
   bool  IsEvaluableAtInObjectSpace(const PointType & point, unsigned int depth = 0,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:93:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::IsInsideInObjectSpace(const PointType&) const’ marked ‘override’, but does not override
   bool  IsInsideInObjectSpace(const PointType & point) const override;
         ^~~~~~~~~~~~~~~~~~~~~
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:107:8: error: ‘void neurolib::SphericalHarmonicSpatialObject::ComputeMyBoundingBox()’ marked ‘override’, but does not override
   void ComputeMyBoundingBox() override;
        ^~~~~~~~~~~~~~~~~~~~
In file included from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/ParametricMeshToSPHARMSpatialObjectFilter.h:17:0,
                 from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/ParametricMeshToSPHARMSpatialObjectFilter.cxx:20:
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:88:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::ValueAtInObjectSpace(const PointType&, double&, unsigned int, const string&) const’ marked ‘override’, but does not override
   bool  ValueAtInObjectSpace(const PointType & point, double & value, unsigned int depth = 0, const std::string & name = "") const override;
         ^~~~~~~~~~~~~~~~~~~~
In file included from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/ParametricMeshToSPHARMSpatialObjectFilter.h:17:0,
                 from /playpen/software/SPHARM-PDM/Libraries/Shape/Algorithms/ParametricMeshToSPHARMSpatialObjectFilter.cxx:20:
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:90:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::IsEvaluableAtInObjectSpace(const PointType&, unsigned int, const string&) const’ marked ‘override’, but does not override
   bool  IsEvaluableAtInObjectSpace(const PointType & point, unsigned int depth = 0,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:93:9: error: ‘bool neurolib::SphericalHarmonicSpatialObject::IsInsideInObjectSpace(const PointType&) const’ marked ‘override’, but does not override
   bool  IsInsideInObjectSpace(const PointType & point) const override;
         ^~~~~~~~~~~~~~~~~~~~~
/playpen/software/SPHARM-PDM/Libraries/Shape/SpatialObject/SphericalHarmonicSpatialObject.h:107:8: error: ‘void neurolib::SphericalHarmonicSpatialObject::ComputeMyBoundingBox()’ marked ‘override’, but does not override
   void ComputeMyBoundingBox() override;
        ^~~~~~~~~~~~~~~~~~~~


However, after I change to 5.1.0 as I asked, I have other problems:
/playpen/software/SPHARM-PDM/Modules/CLI/MetaMeshTools/itkMeshTovtkPolyData.cxx:85:22: error: ‘VERTEX_CELL’ is not a member of ‘itkMeshTovtkPolyData::CellType {aka itk::CellInterface<double, itk::CellTraitsInfo<3, double, double, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 3>, itk::MapContainer<long unsigned int, itk::Point<double, 3> >, std::set<long unsigned int> > >}’
       case CellType::VERTEX_CELL:
                      ^~~~~~~~~~~
/playpen/software/SPHARM-PDM/Modules/CLI/MetaMeshTools/itkMeshTovtkPolyData.cxx:86:22: error: ‘LINE_CELL’ is not a member of ‘itkMeshTovtkPolyData::CellType {aka itk::CellInterface<double, itk::CellTraitsInfo<3, double, double, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 3>, itk::MapContainer<long unsigned int, itk::Point<double, 3> >, std::set<long unsigned int> > >}’
       case CellType::LINE_CELL:
                      ^~~~~~~~~
/playpen/software/SPHARM-PDM/Modules/CLI/MetaMeshTools/itkMeshTovtkPolyData.cxx:87:22: error: ‘POLYGON_CELL’ is not a member of ‘itkMeshTovtkPolyData::CellType {aka itk::CellInterface<double, itk::CellTraitsInfo<3, double, double, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 3>, itk::MapContainer<long unsigned int, itk::Point<double, 3> >, std::set<long unsigned int> > >}’
       case CellType::POLYGON_CELL:
                      ^~~~~~~~~~~~
/playpen/software/SPHARM-PDM/Modules/CLI/MetaMeshTools/itkMeshTovtkPolyData.cxx:89:22: error: ‘TRIANGLE_CELL’ is not a member of ‘itkMeshTovtkPolyData::CellType {aka itk::CellInterface<double, itk::CellTraitsInfo<3, double, double, long unsigned int, long unsigned int, long unsigned int, itk::Point<double, 3>, itk::MapContainer<long unsigned int, itk::Point<double, 3> >, std::set<long unsigned int> > >}’
       case CellType::TRIANGLE_CELL:
                      ^~~~~~~~~~~~~
Thanks,
Zhiyuan
