### ISSUE TITLE
Fix build error when building against VTK9

### ISSUE THREAD

**Issue by jcfr** [NIRALUser/SPHARM-PDM#61]
See https://slicer.cdash.org/index.php?project=SlicerPreview&date=2021-03-10&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=SPHARM-PDM

```
Modules/CLI/MetaMeshTools/vtkPolyDataToitkMesh.cxx:82:26: error: no matching member function for call to 'GetNextCell'
```

```
Modules/CLI/MetaMeshTools/STL2Meta.cxx:93:70: error: invalid initialization of non-const reference of type ‘const vtkIdType*& {aka const long long int*&}’ from an rvalue of type ‘const vtkIdType* {aka const long long int*}’
```

**Comment by allemangD** [comment]
This was fixed in 24addc5. Local build errors I've had since then were due to an unrelated issue with Ninja that I confused for this issue. 

Closing this issue and opening a new one for the Ninja issue. Since that Ninja issue can be easily worked around by using the "Unix Makefiles" generator, we can consider it lower-priority for now.
