### ISSUE TITLE
Windows factory builds failing

### ISSUE THREAD

**Issue by allemangD** [NIRALUser/SPHARM-PDM#68]
Nightly `overload` builds are failing, both for Slicer4 and SlicerPreview:

- Stable: https://slicer.cdash.org/viewBuildError.php?buildid=2472803
- Preview: https://slicer.cdash.org/viewBuildError.php?buildid=2472429

The error indicates to me that `WIN32` is somehow not defined, causing the wrong `#include` directive to be used.

**Comment by jcfr** [comment]
Closing.

Fixed for Slicer Preview in https://github.com/NIRALUser/RigidAlignment/pull/7 integrated in SPHARM-PDM through https://github.com/NIRALUser/GROUPS/pull/33 and https://github.com/NIRALUser/SPHARM-PDM/pull/71

Since we are in the process of releasing Slicer `5.0`, the extension associated with the stable release `4.11.20210226` will not be fixed
